import 'package:isar/isar.dart';

part 'models.g.dart'; // Will be generated by build_runner

@collection
class Bike {
  Id id = Isar.autoIncrement;

  late String name;
  late String brand;
  double initialMileage = 0.0; // km

  @Backlink(to: 'bike')
  final rides = IsarLinks<Ride>();
}

@collection
class Ride {
  Id id = Isar.autoIncrement;

  late DateTime startTime;
  DateTime? endTime;

  // Statistics
  double distance = 0.0; // in kilometers
  double durationSeconds = 0.0;
  double avgSpeed = 0.0; // km/h
  double topSpeed = 0.0; // km/h
  double maxLeanAngle = 0.0; // degrees

  // Weather Snapshot
  String? weatherCondition;
  double? temperatureCelsius;

  // Relationship to points
  @Backlink(to: 'ride')
  final points = IsarLinks<RidePoint>();

  // Relationship to Bike
  final bike = IsarLink<Bike>();
}

@collection
class RidePoint {
  Id id = Isar.autoIncrement;

  late double latitude;
  late double longitude;
  late double speed; // km/h
  late double heading;
  late double altitude;
  late double accuracy;
  late DateTime timestamp;

  // The ride this point belongs to
  final ride = IsarLink<Ride>();
}
